version: '3'

services:
  db:
    image: yobasystems/alpine-mariadb:10.4.13
    container_name: dormitory_db
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    volumes:
      - dormitory_db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dormitory_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
  
  api:
    build: ./api
    container_name: dormitory_api
    restart: always
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./api:/app
    depends_on:
      - db
  
  # ui:
  #   build: ./ui
  #   container_name: dormitory_ui
  #   restart: always
  #   volumes:
  #     - ./ui:/app
  
  nginx:
    build: ./nginx
    container_name: dormitory_nginx
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"

volumes:
  dormitory_db:
